services:
  stats-server:
    build: ./ewm-stats-service/stats-service
    image: stats_image
    container_name: stats_service
    depends_on:
      - stats-db
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:16.1
    container_name: stats_db
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_PASSWORD=ewm-stats
      - POSTGRES_USER=ewm-stats
      - POSTGRES_DB=ewm-stats
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build: ./ewm-main-service
    image: service_image
    container_name: ewm-service
    depends_on:
      - ewm-db
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:16.1
    container_name: ewm_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=ewm-service
      - POSTGRES_USER=ewm-service
      - POSTGRES_DB=ewm-service
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
