server:
  port: ${SERVER_PORT:9090}

spring:
  application:
    name: stats-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ewm-stats}
    username: ${SPRING_DATASOURCE_USERNAME:ewm-stats}
    password: ${SPRING_DATASOURCE_PASSWORD:ewm-stats}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

logging:
  level:
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.springframework.transaction.interceptor: TRACE
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    ru.practicum.statsservice: DEBUG